spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password123@.
    url: jdbc:mysql://localhost:3306/inventory_db #?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    initialization-mode: always
    initialize: true

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop