spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_DATABASE}
    password: ${PASSWORD_DATABASE}
    url: jdbc:mysql://${HOST_DATABASE}:${PORT_DATABASE}/${NAME_DATABASE}_dev
    initialization-mode: always
    initialize: true

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  redis:
    host: ${HOST_REDIS}
    port: ${PORT_REDIS}

  servlet:
    servlet:
      session:
        timeout: 3600000
